src/Entity/EterClan.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EterClanRepository")
 * @Vich\Uploadable
 * @ApiResource()
 */
class EterClan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $clan_name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $clan_members;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $clan_desc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $clan_ban;

    /**
     * @Vich\UploadableField(mapping="clan_ban", fileNameProperty="clan_ban")
     * @var File
     */
    private $ban_pic;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $clan_discord;

    /**
     * @ORM\Column(type="boolean")
     */
    private $clan_recrut;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterGameplay", inversedBy="eterClans")
     */
    private $clan_gameplay;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterUser", mappedBy="user_clan")
     */
    private $eterUsers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterEvent", inversedBy="eterClans")
     */
    private $clan_event;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $clan_slogan;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $clan_update;



    public function __construct()
    {
        $this->clan_gameplay = new ArrayCollection();
        $this->eterUsers = new ArrayCollection();
        $this->clan_event = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClanName(): ?string
    {
        return $this->clan_name;
    }

    public function setClanName(string $clan_name): self
    {
        $this->clan_name = $clan_name;

        return $this;
    }

    public function __toString()
    {
        return $this->clan_name;
    }

    public function getClanMembers(): ?int
    {
        return $this->clan_members;
    }

    public function setClanMembers(int $clan_members): self
    {
        $this->clan_members = $clan_members;

        return $this;
    }

    public function getClanDesc(): ?string
    {
        return $this->clan_desc;
    }

    public function setClanDesc(string $clan_desc): self
    {
        $this->clan_desc = $clan_desc;

        return $this;
    }

    public function getClanBan(): ?string
    {
        return $this->clan_ban;
    }

    public function setClanBan(?string $clan_ban): self
    {
        $this->clan_ban = $clan_ban;

        return $this;
    }

    public function getClanDiscord(): ?string
    {
        return $this->clan_discord;
    }

    public function setClanDiscord(?string $clan_discord): self
    {
        $this->clan_discord = $clan_discord;

        return $this;
    }

    public function getClanRecrut(): ?bool
    {
        return $this->clan_recrut;
    }

    public function setClanRecrut(bool $clan_recrut): self
    {
        $this->clan_recrut = $clan_recrut;

        return $this;
    }


    /**
     * @return Collection|EterGameplay[]
     */
    public function getClanGameplay(): Collection
    {
        return $this->clan_gameplay;
    }

    public function addClanGameplay(EterGameplay $clanGameplay): self
    {
        if (!$this->clan_gameplay->contains($clanGameplay)) {
            $this->clan_gameplay[] = $clanGameplay;
        }

        return $this;
    }

    public function removeClanGameplay(EterGameplay $clanGameplay): self
    {
        if ($this->clan_gameplay->contains($clanGameplay)) {
            $this->clan_gameplay->removeElement($clanGameplay);
        }

        return $this;
    }

    /**
     * @return Collection|EterUser[]
     */
    public function getEterUsers(): Collection
    {
        return $this->eterUsers;
    }

    public function addEterUser(EterUser $eterUser): self
    {
        if (!$this->eterUsers->contains($eterUser)) {
            $this->eterUsers[] = $eterUser;
            $eterUser->addUserClan($this);
        }

        return $this;
    }

    public function removeEterUser(EterUser $eterUser): self
    {
        if ($this->eterUsers->contains($eterUser)) {
            $this->eterUsers->removeElement($eterUser);
            $eterUser->removeUserClan($this);
        }

        return $this;
    }

    /**
     * @return Collection|EterEvent[]
     */
    public function getClanEvent(): Collection
    {
        return $this->clan_event;
    }

    public function addClanEvent(EterEvent $clanEvent): self
    {
        if (!$this->clan_event->contains($clanEvent)) {
            $this->clan_event[] = $clanEvent;
        }

        return $this;
    }

    public function removeClanEvent(EterEvent $clanEvent): self
    {
        if ($this->clan_event->contains($clanEvent)) {
            $this->clan_event->removeElement($clanEvent);
        }

        return $this;
    }

    public function getClanSlogan(): ?string
    {
        return $this->clan_slogan;
    }

    public function setClanSlogan(?string $clan_slogan): self
    {
        $this->clan_slogan = $clan_slogan;

        return $this;
    }

    public function setBanPic(File $clan_ban = null) {
        $this->ban_pic = $clan_ban;
        // ajout d'un champs modif datetime dans la bdd pour forcer la persistance
        if ($clan_ban) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->clan_update = new \DateTime('now');
        }
    }

    public function getBanPic() {
        return $this->ban_pic;
    }

    public function getClanUpdate(): ?\DateTimeInterface
    {
        return $this->clan_update;
    }

    public function setClanUpdate(\DateTimeInterface $clan_update): self
    {
        $this->clan_update = $clan_update;

        return $this;
    }

}

src/Entity/EterUser.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EterUserRepository")
 * @Vich\Uploadable
 * @UniqueEntity(
 * fields = {"user_mail"}, 
 * message = "L'email existe déjà")
 * @ApiResource()
 */
class EterUser implements UserInterface
{
    // définition d'un tableau des rôles => constante
    const ROLE = [
        0 => 'Administrateur',
        1 => 'Utilisateur'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $user_login;

    /**
     * @ORM\Column(type="datetime")
     */
    private $user_date;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $user_mail;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $user_password;

    /**
    * @Assert\EqualTo(propertyPath="user_password", message="Vos mots de passe sont différents")
    */
    public $confirm_user_password;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $user_address;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $user_zip;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $user_city;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $user_discord;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $user_sex;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $statut;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterLabel", inversedBy="eterUsers")
     */
    private $label;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterClan", inversedBy="eterUsers")
     */
    private $user_clan;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterGame", inversedBy="eterUsers", cascade={"persist"})
     */
    private $user_game;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EterStreamer", mappedBy="eterUser")
     */
    private $user_stream;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterEvent", mappedBy="event_orga")
     */
    private $eterEvents;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EterComment", mappedBy="com_user")
     */
    private $eterComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EterContent", mappedBy="content_user")
     */
    private $eterContents;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $user_description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $user_update;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_avatar;

    /**
     * @Vich\UploadableField(mapping="profil_pic", fileNameProperty="user_avatar")
     * @var File
     */
    private $user_pic;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_role;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $date_inscr;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $date_lien;

    /**
     * @ORM\ManyToMany(targetEntity=EterProduct::class, mappedBy="eter_user")
     */
    private $eterProducts;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $user_order_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $user_desactivate;

    public function __construct()
    {
        $this->user_date = new \DateTime('Europe/Paris');
        $this->role = new ArrayCollection();
        $this->user_clan = new ArrayCollection();
        $this->user_game = new ArrayCollection();
        $this->user_stream = new ArrayCollection();
        $this->eterEvents = new ArrayCollection();
        $this->eterComments = new ArrayCollection();
        $this->eterContents = new ArrayCollection();
        $this->eterProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserLogin(): ?string
    {
        return $this->user_login;
    }

    public function setUserLogin(string $user_login): self
    {
        $this->user_login = $user_login;

        return $this;
    }

    public function __toString()
    {
        return $this->user_login;
    }

    public function getUserDate(): ?\DateTimeInterface
    {
        return $this->user_date;
    }

    public function setUserDate(\DateTimeInterface $user_date): self
    {
        $this->user_date = $user_date;

        return $this;
    }

    public function getUserMail(): ?string
    {
        return $this->user_mail;
    }

    public function setUserMail(string $user_mail): self
    {
        $this->user_mail = $user_mail;

        return $this;
    }

    public function getUserPassword(): ?string
    {
        return $this->user_password;
    }

    public function setUserPassword(string $user_password): self
    {
        $this->user_password = $user_password;

        return $this;
    }

    public function getUserAddress(): ?string
    {
        return $this->user_address;
    }

    public function setUserAddress(?string $user_address): self
    {
        $this->user_address = $user_address;

        return $this;
    }

    public function getUserZip(): ?string
    {
        return $this->user_zip;
    }

    public function setUserZip(?string $user_zip): self
    {
        $this->user_zip = $user_zip;

        return $this;
    }

    public function getUserCity(): ?string
    {
        return $this->user_city;
    }

    public function setUserCity(?string $user_city): self
    {
        $this->user_city = $user_city;

        return $this;
    }

    public function getUserDiscord(): ?string
    {
        return $this->user_discord;
    }

    public function setUserDiscord(string $user_discord): self
    {
        $this->user_discord = $user_discord;

        return $this;
    }

    public function getUserSex(): ?string
    {
        return $this->user_sex;
    }

    public function setUserSex(?string $user_sex): self
    {
        $this->user_sex = $user_sex;

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(?bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUserRole(): ?string
    {
        return $this->user_role;
    }

    public function setUserRole(?string $user_role): self
    {
        // role automatique par défaut
        $user_role = 'Utilisateur';
        $this->user_role = $user_role;

        return $this;
    }

    /**
     * @return Collection|EterLabel[]
     */
    public function getLabel(): Collection
    {
        return $this->label;
    }

    public function addLabel(EterLabel $label): self
    {
        if (!$this->label->contains($label)) {
            $this->label[] = $label;
        }

        return $this;
    }

    public function removeUserLabel(EterLabel $userLabel): self
    {
        if ($this->label->contains($userLabel)) {
            $this->label->removeElement($userLabel);
        }

        return $this;
    }

    /**
     * @return Collection|EterClan[]
     */
    public function getUserClan(): Collection
    {
        return $this->user_clan;
    }

    public function addUserClan(EterClan $userClan): self
    {
        if (!$this->user_clan->contains($userClan)) {
            $this->user_clan[] = $userClan;
        }

        return $this;
    }

    public function removeUserClan(EterClan $userClan): self
    {
        if ($this->user_clan->contains($userClan)) {
            $this->user_clan->removeElement($userClan);
        }

        return $this;
    }

    /**
     * @return Collection|EterGame[]
     */
    public function getUserGame(): Collection
    {
        return $this->user_game;
    }

    public function addUserGame(EterGame $userGame): self
    {
        if (!$this->user_game->contains($userGame)) {
            $this->user_game[] = $userGame;
        }

        return $this;
    }

    public function removeUserGame(EterGame $userGame): self
    {
        if ($this->user_game->contains($userGame)) {
            $this->user_game->removeElement($userGame);
        }

        return $this;
    }

    /**
     * @return Collection|EterStreamer[]
     */
    public function getUserStream(): Collection
    {
        return $this->user_stream;
    }

    public function addUserStream(EterStreamer $userStream): self
    {
        if (!$this->user_stream->contains($userStream)) {
            $this->user_stream[] = $userStream;
            $userStream->setEterUser($this);
        }

        return $this;
    }

    public function removeUserStream(EterStreamer $userStream): self
    {
        if ($this->user_stream->contains($userStream)) {
            $this->user_stream->removeElement($userStream);
            // set the owning side to null (unless already changed)
            if ($userStream->getEterUser() === $this) {
                $userStream->setEterUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|EterEvent[]
     */
    public function getEterEvents(): Collection
    {

templates/eter_user/_delete_form.html.twig
<form method="post" name="delete" action="{{ path('eter_user_delete', {'id': eter_user.id}) }}" onsubmit="deleteForm()">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ eter_user.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

<script>
    function deleteForm() {
        event.preventDefault(); // Empêche la soumission du formulaire
        var form = document.forms["delete"];
        swal({
            title: "Etes-vous certain ?",
            text: "Une fois supprimé, vous ne pourrez plus voir votre profil !",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    swal("Votre profil a été supprimé avec succès !", {
                        button: false,
                        icon: "success"
                    });
                    form.submit();
                } else {
                    swal("Votre profil n'a pas été supprimé !", {
                        button: "Ouf !",
                        icon: "error"
                    });
                }
            });
    }
</script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

templates/eter_user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/eter_user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profils utilisateurs{% endblock %}

{% block body %}
<table>
    <thead>
    <tr>
        <th>Pseudo</th>
        <th>Photo de profil</th>
        <th>Tags</th>
        <th>clan</th>
        <th>Adresse Mail</th>
        <th>Etat</th>
    </tr>
    </thead>

    <tbody v-for="user in info" :key="user.id">
    <tr>
        <td>${user.userLogin}</td>
    </tr>
    </tbody>
</table>









{#    <div class="row d-flex justify-content-center">#}

{#    {% for eter_user in eter_users %}#}

{#    <div id="cards" class="card mb-2 ml-2 mr-2">#}

{#        <div class="card-header">#}
{#                {% if eter_user.userAvatar %}#}

{#                <img id="image_index" src="{{ asset('img/upload/profil_pic/' ~ eter_user.userAvatar) | imagine_filter('profil') }}" alt="default_profil">#}

{#                {% else %}#}

{#                <img id="image_index" src="{{ asset('img/upload/profil_pic/default-profil.jpg') | imagine_filter('profil') }}" alt="default_profil">#}

{#                {% endif %}#}
{#        </div>#}

{#        <div id="eter" class="card-body">#}
{#            <p class="eters">Login : {{ eter_user.userLogin }}</p>#}
{#            <p class="eters">Email : {{ eter_user.userMail }}</p>#}
{#            <p class="eters">ID Discord : {{ eter_user.userDiscord }}</p>#}
{#            <p class="eters">Adresse : {{ eter_user.userAddress }}<p>#}
{#            <p class="eters">Code Postal : {{ eter_user.userZip }}</p>#}
{#            <p class="eters">Ville : {{ eter_user.userCity }}</p>#}
{#            <p class="eters">Sexe : {{ eter_user.userSex }}</p>#}
{#            <p class="eters">Description : {{ eter_user.userDescription }}</p>#}
{#            #}{#<p class="eters">Votre(Vos) clan(s) : {{ eter_user.user_clan }}</p>#}
{#            <p class="eters">Votre(Vos) jeu(x) : {{ eter_user.user_game }}</p>#}
{#            <p class="eters">Votre(Vos) évènement(s) : {{ eter_user.eterEvents }}</p>#}
{#            <p class="eters">Votre(Vos) stream(s) : {{ eter_user.user_stream }}</p>#}
{#            <p class="eters">Rôle : {{ eter_user.userRole }}</p>#}
{#        </div>#}

{#        <div class="card-footer">#}
{#        <button id="show" type="button" class="btn btn-info"><a class="profil" href="{{ path('eter_user_show', {'id': eter_user.id}) }}">AFFICHER</a></button>#}
{#        <button id="edit" type="button" class="btn btn-danger"><a class="profil" href="{{ path('eter_user_edit', {'id': eter_user.id}) }}">MODIFIER</a></button>#}
{#        </div>#}

{#    </div>#}
    
    {% endfor %}

    </div>
    
{% endblock %}

templates/eter_user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New EterUser{% endblock %}

{% block body %}
    <h1>Create new EterUser</h1>

    {{ include('eter_user/_form.html.twig') }}

    <a href="{{ path('eter_user_index') }}">back to list</a>
{% endblock %}

templates/eter_user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage du profil{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row profil">
            <div class="col s4 offset-s2">
                    {% if app.user.userAvatar is same as(null) %}
                        <a href="#user">
                            <img class="circle profil-pic"
                                 src="{{ asset('img/upload/profil_pic/default-profil.jpg') }}" alt="Photo de profil de {{ app.user.userLogin }}" title="Photo de profil par défaut">
                        </a>
                    {% else %}
                        <a href="#user">
                            <img class="circle profil-pic"
                                 src="{{ asset('img/upload/profil_pic/' ~ app.user.userAvatar) }}" alt="Photo de profil de {{ app.user.userLogin }}" title="Photo de profil">
                        </a>
                    {% endif %}
            </div>
            <div class="col s6">
                <div class="row">
                    <div class="col s3">
                        <p class="white-text">Pseudo : </p>
                    </div>
                    <div class="col s9">
                        <p class="white-text">{{ app.user.userLogin }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s3">
                        <p class="white-text">Adresse Email : </p>
                    </div>
                    <div class="col s9">
                        <p class="white-text">{{ app.user.userMail }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s3">
                        <p class="white-text">Discord : </p>
                    </div>
                    <div class="col s9">
                        <p class="white-text">{{ app.user.userDiscord }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s3">
                        <p class="white-text">Discord : </p>
                    </div>
                    <div class="col s9">
                        <p class="white-text">{{ app.user.userDiscord }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s3">
                        <p class="white-text">Mes clans : </p>
                    </div>
                    <div class="col s9">
                        <div class="row">
                            {% for clan in app.user.userClan %}
                                <div class="col s3">
                                    <p class="white-text">{{ (clan.clanName) == null ? 'Pas de clan' : clan.clanName }}</p>
                                </div>
                                <div class="col s9">

                                    <img src="{{ asset('img/upload/ban/' ~ clan.clanBan) | imagine_filter('profil') }}"
                                         class="circle responsive-img"
                                         alt="Bannière du clan {{ clan.clanName }}"
                                         title="Bannière du clan {{ clan.clanName }}">
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row profil">
            <div class="col s6 center-align">
                <p class="white-text">
                    Description :
                </p>
            </div>
            <div class="col s6">
                <p class="white-text">
                    {{ (app.user.userDescription == null) ? 'Pas de description' : app.user.userDescription }}
                </p>
            </div>
        </div>
        <div class="row profil">
            <div class="col s12 center-align">
                <h2
                        class="white-text">Mes informations personnelles</h2>
            </div>
        </div>
        <div class="row">
            <div class="col s3 center-align">
                <p class="white-text">Adresse :</p>
            </div>
            <div class="col s3 left-align">
                <p class="white-text">{{ (app.user.userAddress) == null ? 'Pas d\'adresse communiquée ' : app.user.userAddress }}</p>
            </div>
            <div class="col s3 center-align">
                <p class="white-text">Code postal :</p>
            </div>
            <div class="col s3 left-align">
                <p class="white-text">{{ (app.user.userZip) == null ? 'Pas de code postal ' : app.user.userZip }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col s3 center-align">
                <p class="white-text">Ville :</p>
            </div>
            <div class="col s3 left-align">
                <p class="white-text">{{ (app.user.userCity) == null ? 'Pas de ville communiquée ' : app.user.userCity }}</p>
            </div>
            <div class="col s3 center-align">
                <p class="white-text">Mes tags :</p>
            </div>
            <div class="col s3 left-align">
                <p class="white-text">Inscris depuis le : {{ app.user.userDate | date('d/m/Y') }}</p>
            </div>
        </div>
    </div>
    {# <div class="card"> #}
    {# <h5 class="card-title">Votre profil</h5> #}
    {# <div id ="cardprofil" class="row no-gutters"> #}
    {# <div id="show1" class="col-md-12"> #}
    {# {% if eter_user.userAvatar %} #}

    {# #}

    {# {% else %} #}

    {# <img id="image" src="{{ asset('img/upload/profil_pic/default-profil.jpg') | imagine_filter('profil') }}" alt="default_profil"> #}

    {# {% endif %} #}
    {# </div> #}
    {# <div class="col-md-12"> #}
    {# <div class="card-body"> #}
    {# <div id="rens1" class="card-text">Login</div> #}
    {# <div id="edit_rens1">{{ eter_user.userLogin }}</div> #}
    {# <br> #}

    {# <div id="rens2" class="card-text">Email</div> #}
    {# <div id="edit_rens2">{{ eter_user.userMail }}</div> #}
    {# <br> #}

    {# <div id="rens3" class="card-text">ID Discord</div> #}
    {# <div id="edit_rens3">{{ eter_user.userDiscord }}</div> #}
    {# <br> #}

    {# <div id="rens4" class="card-text">Adresse</div> #}
    {# <div contentEditable=false data-text="Pas encore d'adresse..." id="edit_rens4">{{ eter_user.userAddress }}</div> #}
    {# <br> #}

    {# <div id="rens5" class="card-text">Code Postal</div> #}
    {# <div contentEditable=false data-text="Pas encore de code postal..." id="edit_rens5">{{ eter_user.userZip }}</div> #}
    {# <br> #}

    {# <div id="rens6" class="card-text">Ville</div> #}
    {# <div contentEditable=false data-text="Pas encore de ville..." id="edit_rens6">{{ eter_user.userCity }}</div> #}
    {# <br> #}

    {# <div id="rens7" class="card-text">Sexe</div> #}
    {# <div contentEditable=false data-text="Pas encore renseigné..." id="edit_rens7">{{ eter_user.userSex }}</div> #}
    {# <br> #}

    {# <div id="rens8" class="card-text">Description</div> #}
    {# <div contentEditable=false data-text="Pas encore de description..." id="edit_rens8">{{ eter_user.userDescription }}</div> #}
    {# <br> #}

    {# #}{# <div id="rens9" class="card-text">Votre(Vos) clan(s)</div> #}
    {# <div contentEditable=false data-text="Pas encore de clan..." id="edit_rens9">{{ eter_user.user_clan }}</div> #}
    {# <br> #}

    {# <div id="rens10" class="card-text">Votre(Vos) jeu(x)</div> #}
    {# <div contentEditable=false data-text="Pas encore de clan..." id="edit_rens10">{{ eter_user.user_game }}</div> #}
    {# <br> #}

    {# <div id="rens11" class="card-text">Votre(Vos) évènement(s)</div> #}
    {# <div contentEditable=false data-text="Pas encore d'évènements..." id="edit_rens11">{{ eter_user.eterEvents }}</div> #}
    {# <br> #}
    {# #}
    {# <div id="rens12" class="card-text">Votre(Vos) stream(s)</div> #}
    {# <div contentEditable=false data-text="Pas encore de stream..." id="edit_rens12">{{ eter_user.user_stream }}</div> #}
    {# <br> #}

    {# <div id="rens13" class="card-text">Rôle</div> #}
    {# <div id="edit_rens13">{{ eter_user.userRole }}</div> #}
    {# </div> #}
    {# </div> #}
    {# </div> #}
    {# <div class="row"> #}
    {# <div class="col-12" id="modifier"> #}
    {# <a class="btn btn-success float-right" href="{{ path('eter_user_edit', {'id': eter_user.id}) }}">Modifier votre profil</a> #}
    {# <a class="btn btn-info float-right" href="{{ path('home') }}">Retour</a> #}
    {# </div> #}
    {# </div> #}
    {# </div> #}

    </div>
{% endblock %}