src/Entity/EterGame.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Scalar\String_;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EterGameRepository")
 * @Vich\Uploadable
 * @ApiResource()
 */
class EterGame
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $game_name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterUser", mappedBy="user_game")
     */
    private $eterUsers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EterGender", inversedBy="eterGames")
     */
    private $game_gender;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $game_pic;

    /**
     * @Vich\UploadableField(mapping="game", fileNameProperty="game_pic")
     * @var File
     */
    private $pic;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $game_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $game_background;

    /**
     * @Vich\UploadableField (mapping="game_background", fileNameProperty="game_background")
     * @var File
     */
    private $background;

    public function __construct()
    {
        $this->eterUsers = new ArrayCollection();
        $this->game_gender = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameName(): ?string
    {
        return $this->game_name;
    }

    public function setGameName(string $game_name): self
    {
        $this->game_name = $game_name;

        return $this;
    }

    public function __toString()
    {
        return $this->game_name;
    }
    /**
     * @return Collection|EterUser[]
     */
    public function getEterUsers(): Collection
    {
        return $this->eterUsers;
    }

    public function addEterUser(EterUser $eterUser): self
    {
        if (!$this->eterUsers->contains($eterUser)) {
            $this->eterUsers[] = $eterUser;
            $eterUser->addUserGame($this);
        }

        return $this;
    }

    public function removeEterUser(EterUser $eterUser): self
    {
        if ($this->eterUsers->contains($eterUser)) {
            $this->eterUsers->removeElement($eterUser);
            $eterUser->removeUserGame($this);
        }

        return $this;
    }

    /**
     * @return Collection|EterGender[]
     */
    public function getGameGender(): Collection
    {
        return $this->game_gender;
    }

    public function addGameGender(EterGender $gameGender): self
    {
        if (!$this->game_gender->contains($gameGender)) {
            $this->game_gender[] = $gameGender;
        }

        return $this;
    }

    public function removeGameGender(EterGender $gameGender): self
    {
        if ($this->game_gender->contains($gameGender)) {
            $this->game_gender->removeElement($gameGender);
        }

        return $this;
    }

    public function getGamePic(): ?string
    {
        return $this->game_pic;
    }

    public function setGamePic(?string $game_pic): self
    {
      $this->game_pic = $game_pic;
        return $this;
    }

    public function setPic(File $game_pic = null)
    {
        $this->pic = $game_pic;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($game_pic) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getPic()
    {
        return $this->pic;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getGameDescription(): ?string
    {
        return $this->game_description;
    }

    public function setGameDescription(?string $game_description): self
    {
        $this->game_description = $game_description;

        return $this;
    }

    public function getGameBackground(): ?string
    {
        return $this->game_background;
    }

    public function setGameBackground(?string $game_background): self
    {
        $this->game_background = $game_background;

        return $this;
    }
    public function setBackground(File $game_background = null)
    {
        $this->pic = $game_background;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($game_background) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getBackground()
    {
        return $this->pic;
    }
}

src/Form/EterGameType.php
<?php

namespace App\Form;

use App\Entity\EterGame;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EterGameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('game_name')
            ->add('pic', FileType::class, [
                'mapped' => false,
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EterGame::class,
        ]);
    }
}

src/Controller/EterGameController.php
<?php

namespace App\Controller;

use App\Entity\EterGame;
use App\Form\EterGameType;
use App\Repository\EterGameRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/eter/game")
 */
class EterGameController extends AbstractController
{
    /**
     * @Route("/", name="eter_game_index", methods={"GET"})
     * @param EterGameRepository $eterGameRepository
     * @return Response
     */
    public function index(EterGameRepository $eterGameRepository): Response
    {
        return $this->render('eter_game/index.html.twig', [
            'games' => $eterGameRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="eter_game_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $eterGame = new EterGame();
        $form = $this->createForm(EterGameType::class, $eterGame);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($eterGame);
            $entityManager->flush();

            return $this->redirectToRoute('eter_game_index');
        }

        return $this->render('eter_game/new.html.twig', [
            'eter_game' => $eterGame,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="eter_game_show", methods={"GET"})
     * @param EterGame $eterGame
     * @return Response
     */
    public function show(EterGame $eterGame): Response
    {
        return $this->render('eter_game/show.html.twig', [
            'game' => $eterGame,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="eter_game_edit", methods={"GET","POST"})
     * @param Request $request
     * @param EterGame $eterGame
     * @return Response
     */
    public function edit(Request $request, EterGame $eterGame): Response
    {
        $form = $this->createForm(EterGameType::class, $eterGame);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('eter_game_index');
        }

        return $this->render('eter_game/edit.html.twig', [
            'eter_game' => $eterGame,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="eter_game_delete", methods={"DELETE"})
     */
    public function delete(Request $request, EterGame $eterGame): Response
    {
        if ($this->isCsrfTokenValid('delete'.$eterGame->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($eterGame);
            $entityManager->flush();
        }

        return $this->redirectToRoute('eter_game_index');
    }
}

templates/eter_game/_delete_form.html.twig
<form method="post" action="{{ path('eter_game_delete', {'id': game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button class="btn">Delete</button>
</form>

templates/eter_game/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/eter_game/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit EterGame{% endblock %}

{% block body %}
    <h1>Edit EterGame</h1>

    {{ include('eter_game/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('eter_game_index') }}">back to list</a>

    {{ include('eter_game/_delete_form.html.twig') }}
{% endblock %}

templates/eter_game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EterGame index{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="hide-on-small-only">
        {% for game in games %}
        <div class="row">
            <div class="col s12">
                <div class="stat" style="background-image: url('{{ asset('img/upload/game/' ~ game.gamePic) }}')">
                    <div class="overlay valign-wrapper">
                        <div class="row valign-wrapper">
                            <div class="col s3">
                                <p class="white-text flow-text stat-title">{{ game.gameName }}</p>
                            </div>
                            <div class="vdivider"></div>
                            <div class="col s4">
                                <div class="row">
                                    <div class="col s12">
                                        <p class="white-text">{{ game.gameDescription }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s12 center-align">
                                        <a href="{{ path('eter_game_show', {'id' : game.id}) }}"
                                           class="waves-effect waves-light btn btn-rounded purple darken-1">En
                                            savoir plus</a>
                                    </div>
                                </div>
                            </div>
                            <div class="vdivider"></div>
                            <div class="col s4">
                                <p class="white-text">
                                    Jacks fall with endurance at the dead singapore! Pressure at the planet that is
                                    when
                                    cold suns harvest.
                                    Freedom doesn’t earthly forget any lama — but the body is what lures. Rinse
                                    eleven
                                    oz of popcorn in eight and a half teaspoons of coffee.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
{#        <div class="row">#}
{#            <div class="col s12">#}
{#                <div class="stat" style="background-image: url({{ asset('img/background/wh_40k.jpg') }})">#}
{#                    <div class="overlay valign-wrapper">#}
{#                        <div class="row valign-wrapper">#}
{#                            <div class="col l3 s12">#}
{#                                <p class="white-text flow-text stat-title">Stat</p>#}
{#                            </div>#}
{#                            <div class="vdivider"></div>#}
{#                            <div class="col s4">#}
{#                                <div class="row">#}
{#                                    <div class="col s12">#}
{#                                        <p class="white-text">#}
{#                                            Jacks fall with endurance at the dead singapore! Pressure at the planet#}
{#                                            that is#}
{#                                            when#}
{#                                            cold suns harvest.#}
{#                                            Freedom doesn’t earthly forget any lama — but the body is what lures.#}
{#                                            Rinse#}
{#                                            eleven#}
{#                                            oz of popcorn in eight and a half teaspoons of coffee.#}
{#                                        </p>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="row">#}
{#                                    <div class="col s12 center-align">#}
{#                                        <a href=" "#}
{#                                           class="waves-effect waves-light btn btn-rounded purple darken-1">En#}
{#                                            savoir plus</a>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="vdivider"></div>#}
{#                            <div class="col l4 s12">#}
{#                                <p class="white-text">#}
{#                                    Jacks fall with endurance at the dead singapore! Pressure at the planet that is#}
{#                                    when#}
{#                                    cold suns harvest.#}
{#                                    Freedom doesn’t earthly forget any lama — but the body is what lures. Rinse#}
{#                                    eleven#}
{#                                    oz of popcorn in eight and a half teaspoons of coffee.#}
{#                                </p>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <div class="row">#}
{#            <div class="col s12">#}
{#                <div class="stat" style="background-image: url({{ asset('img/background/destiny.png') }})">#}
{#                    <div class="overlay valign-wrapper">#}
{#                        <div class="row valign-wrapper">#}
{#                            <div class="col s3">#}
{#                                <p class="white-text flow-text stat-title">Stat</p>#}
{#                            </div>#}
{#                            <div class="vdivider"></div>#}
{#                            <div class="col s4">#}
{#                                <div class="row">#}
{#                                    <div class="col s12">#}
{#                                        <p class="white-text">#}
{#                                            Jacks fall with endurance at the dead singapore! Pressure at the planet#}
{#                                            that is#}
{#                                            when#}
{#                                            cold suns harvest.#}
{#                                            Freedom doesn’t earthly forget any lama — but the body is what lures.#}
{#                                            Rinse#}
{#                                            eleven#}
{#                                            oz of popcorn in eight and a half teaspoons of coffee.#}
{#                                        </p>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="row">#}
{#                                    <div class="col s12 center-align">#}
{#                                        <a href=" "#}
{#                                           class="waves-effect waves-light btn btn-rounded purple darken-1">En#}
{#                                            savoir plus</a>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="vdivider"></div>#}
{#                            <div class="col s4">#}
{#                                <p class="white-text">#}
{#                                    Jacks fall with endurance at the dead singapore! Pressure at the planet that is#}
{#                                    when#}
{#                                    cold suns harvest.#}
{#                                    Freedom doesn’t earthly forget any lama — but the body is what lures. Rinse#}
{#                                    eleven#}
{#                                    oz of popcorn in eight and a half teaspoons of coffee.#}
{#                                </p>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
    </div>
    <div class="hide-on-med-and-up">
        <div class="card mobil-card">
            <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" src="{{ asset('img/background/lol.jpg') }}">
            </div>
            <div class="card-content">
                <div class="row">
                    <div class="col s6">
                        <span class="card-title activator white-text"><i
                                    class="material-icons left">more_vert</i></span>
                    </div>
                    <div class="col s6">
                        <span class="card-title right white-text">LOL</span>
                    </div>
                </div>
                <p><a href="#">Voir plus</a></p>
            </div>
            <div class="card-reveal mobil-card">
                <div class="row">
                    <div class="col s6">
                        <span class="card-title white-text"><i class="material-icons left white-text">close</i></span>
                    </div>
                    <div class="col s6">
                        <span class="card-title white-text right">LOL</span>
                    </div>
                </div>
                <p class="white-text">
                    Jacks fall with endurance at the dead singapore! Pressure at the planet that is
                    when
                    cold suns harvest.
                    Freedom doesn’t earthly forget any lama — but the body is what lures. Rinse
                    eleven
                    oz of popcorn in eight and a half teaspoons of coffee.
                </p>
            </div>
        </div>
        <div class="hide-on-med-and-up">
            <div class="card mobil-card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="{{ asset('img/background/wh_40k.jpg') }}">
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col s6">
                            <span class="card-title activator white-text"><i
                                        class="material-icons left">more_vert</i></span>
                        </div>
                        <div class="col s6">
                            <span class="card-title right white-text">WarHammer 40k</span>
                        </div>
                    </div>
                    <p><a href="#">Voir plus</a></p>
                </div>
                <div class="card-reveal mobil-card">
                    <div class="row">
                        <div class="col s6">
                            <span class="card-title white-text"><i
                                        class="material-icons left white-text">close</i></span>
                        </div>
                        <div class="col s6">
                            <span class="card-title white-text right">WarHammer 40k</span>
                        </div>
                    </div>
                    <p class="white-text">
                        Jacks fall with endurance at the dead singapore! Pressure at the planet that is
                        when
                        cold suns harvest.
                        Freedom doesn’t earthly forget any lama — but the body is what lures. Rinse
                        eleven
                        oz of popcorn in eight and a half teaspoons of coffee.
                    </p>
                </div>
            </div>
            <div class="hide-on-med-and-up">
                <div class="card mobil-card">
                    <div class="card-image waves-effect waves-block waves-light">
                        <img class="activator" src="{{ asset('img/background/destiny.png') }}">
                    </div>
                    <div class="card-content">
                        <div class="row">
                            <div class="col s6">
                                <span class="card-title activator white-text"><i
                                            class="material-icons left">more_vert</i></span>
                            </div>
                            <div class="col s6">
                                <span class="card-title right white-text">Destiny</span>
                            </div>
                        </div>
                        <p><a href="#">Voir plus</a></p>
                    </div>
                    <div class="card-reveal mobil-card">
                        <div class="row">
                            <div class="col s6">
                                <span class="card-title white-text"><i class="material-icons left white-text">close</i></span>
                            </div>
                            <div class="col s6">
                                <span class="card-title white-text right">Destiny</span>
                            </div>
                        </div>
                        <p class="white-text">
                            Jacks fall with endurance at the dead singapore! Pressure at the planet that is
                            when
                            cold suns harvest.
                            Freedom doesn’t earthly forget any lama — but the body is what lures. Rinse
                            eleven
                            oz of popcorn in eight and a half teaspoons of coffee.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        {% endblock %}

templates/eter_game/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New EterGame{% endblock %}

{% block body %}
    <h1>Create new EterGame</h1>

    {{ include('eter_game/_form.html.twig') }}

    <a href="{{ path('eter_game_index') }}">back to list</a>
{% endblock %}

templates/eter_game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ game.gameName}}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col s4 offset-s2">
            <h1 class="light-blue-text">{{ game.gameName | upper}}</h1>
        </div>
    </div>
<div class="row">
    <div class="col s4 offset-s2 center-align">
        <h2 class="white-text title-background">MES COUILLES</h2>
    </div>
</div>
    <div class="row">
        <div class="col s5 offset-s1">
            <img src="{{ asset('img/upload/game/' ~ game.gamePic) }}" alt="image de {{ game.gameName }}" class="responsive-img">
        </div>
        <div class="col s4 offset-s1">
            <p class="white-text">{{ game.gameDescription }}</p>
        </div>
    </div>

   <div class="row">
       <div class="col s12 center-align">
           <a href="{{ path('eter_game_index') }}" class="waves-effect waves-light btn btn-rounded blue darken-1">retour</a>
       </div>
   </div>


{% endblock %}