src/Entity/EterProduct.php
<?php

namespace App\Entity;

use App\Repository\EterProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EterProductRepository::class)
 */
class EterProduct
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $product_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $product_image;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $product_price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $product_quantity;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $product_description;

    /**
     * @ORM\ManyToMany(targetEntity=EterUser::class, inversedBy="eterProducts")
     */
    private $eter_user;

    public function __construct()
    {
        $this->eter_user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductTitle(): ?string
    {
        return $this->product_title;
    }

    public function setProductTitle(string $product_title): self
    {
        $this->product_title = $product_title;

        return $this;
    }

    public function getProductImage(): ?string
    {
        return $this->product_image;
    }

    public function setProductImage(?string $product_image): self
    {
        $this->product_image = $product_image;

        return $this;
    }

    public function getProductPrice(): ?float
    {
        return $this->product_price;
    }

    public function setProductPrice(int $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    public function getProductQuantity(): ?int
    {
        return $this->product_quantity;
    }

    public function setProductQuantity(?int $product_quantity): self
    {
        $this->product_quantity = $product_quantity;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->product_description;
    }

    public function setProductDescription(?string $product_description): self
    {
        $this->product_description = $product_description;

        return $this;
    }

    /**
     * @return Collection|EterUser[]
     */
    public function getEterUser(): Collection
    {
        return $this->eter_user;
    }

    public function addEterUser(EterUser $eterUser): self
    {
        if (!$this->eter_user->contains($eterUser)) {
            $this->eter_user[] = $eterUser;
        }

        return $this;
    }

    public function removeEterUser(EterUser $eterUser): self
    {
        if ($this->eter_user->contains($eterUser)) {
            $this->eter_user->removeElement($eterUser);
        }

        return $this;
    }

}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Repository\EterProductRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    /**
     * @Route("/product", name="product_index")
     * @param EterProductRepository $eterProductRepository
     * @return Response
     */
    public function index(EterProductRepository $eterProductRepository )
    {
        $inProgress = false;
        return $this->render('product/list.html.twig', [
            'products' => $eterProductRepository->findAll(),
            'inProgress' => $inProgress
        ]);
    }
}

templates/product/list.html.twig
{% extends'base.html.twig' %}

{% block title %}Liste des produits{% endblock %}

{% block body %}

<div id="titre1">
    <h1>Les produits</h1>
</div>

<div class="row d-flex justify-content-center">

{% for eter_product in products %}

    <div id="list" class="card text-center mb-2 ml-2 border border-info">
        <div id="card_header" class="card-header">
            <img src="{{ asset('img/upload/product/' ~ eter_product.productImage) }}" alt="Image de {{ eter_product.productTitle }}" class="card-img-top">
        </div>

        <div id="card_body" class="card-body">

            <h3 id="product_title">{{ eter_product.productTitle }}</h3>

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#staticBackdrop{{eter_product.id}}">
            <i class="fas fa-info-circle mr-1"></i>PLUS D'INFOS
            </button>

            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop{{eter_product.id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modal_title" class="modal-title" id="staticBackdropLabel">{{ eter_product.productTitle }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modal_body" class="modal-body">
                    {{ eter_product.productDescription }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">FERMER</button>
                </div>
                </div>
            </div>
            </div>

        </div>

        <div class="card-footer">
            <p id="product_price"> Prix : {{ eter_product.productPrice | number_format(2,',','.') }} &euro;</p>
            {% if app.user %}
                <a href="{{ path('cart_add', {'id': eter_product.id}) }}"class="btn btn-success"><i class="fas fa-shopping-cart mr-1"></i>AJOUTER</a>
            {% else %}
                <a href="{{ path('login') }}"class="btn btn-success"><i class="fas fa-shopping-cart mr-1"></i>AJOUTER</a>
            {% endif %}
        </div>

    </div>

{% endfor %}

</div>

{% endblock %}